CREATE TABLE IF NOT EXISTS Houses(
	house_id SERIAL PRIMARY KEY,
	name VARCHAR(30) UNIQUE NOT NULL,
	password VARCHAR(128) NOT NULL,
	created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Users(
	user_id SERIAL PRIMARY KEY,
	house_id INTEGER REFERENCES Houses (house_id),
	email_addr VARCHAR(128) UNIQUE NOT NULL,
	username VARCHAR(128) UNIQUE NOT NULL,
	password VARCHAR(128) NOT NULL,
	created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Tasks(
	task_id SERIAL PRIMARY KEY,
	name VARCHAR(128),
	house_id INTEGER NOT NULL REFERENCES Houses (house_id) ON DELETE CASCADE,
	user_id INTEGER REFERENCES Users (user_id),
	finished_on TIMESTAMP WITH TIME ZONE,
	status BOOLEAN DEFAULT FALSE,
	created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Items(
	item_id SERIAL PRIMARY KEY,
	name VARCHAR(128),
	house_id INTEGER NOT NULL REFERENCES Houses (house_id) ON DELETE CASCADE,
	quantity INTEGER DEFAULT 1,
	price numeric(8, 2) NOT NULL,
	bought BOOLEAN DEFAULT FALSE,
	bought_on TIMESTAMP,
	created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

